services:
  app:
    container_name: be-kampungdigital-prod
    build:
      target: production
    environment:
      - NODE_ENV=production
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
